
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET.skillconfig
{
    public sealed partial class ActionParam : ET.Object
    {
        public ActionParam(int Id, string Name, string Kind, float Value, int IntervalMs, int? BuffId) 
        {
            this.Id = Id;
            this.Name = Name;
            this.Kind = Kind;
            this.Value = Value;
            this.IntervalMs = IntervalMs;
            this.BuffId = BuffId;
            EndInit();
        }

        public readonly int Id;
        public readonly string Name;
        public readonly string Kind;
        public readonly float Value;
        public readonly int IntervalMs;
        public readonly int? BuffId;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

