
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET.skillconfig
{
    public sealed partial class AreaParam : ET.Object
    {
        public AreaParam(int Id, string Name, System.Collections.Generic.List<float> HalfExtents, int TotalTimeMs, int TickTimeMs, System.Collections.Generic.List<int> EnterActions, System.Collections.Generic.List<int> TickActions, System.Collections.Generic.List<int> ExitActions, skillconfig.HitReaction HitReaction, int ViewAnimId, int? ViewBackAnimId, int? ViewEndAnimId) 
        {
            this.Id = Id;
            this.Name = Name;
            this.HalfExtents = HalfExtents;
            this.TotalTimeMs = TotalTimeMs;
            this.TickTimeMs = TickTimeMs;
            this.EnterActions = EnterActions;
            this.TickActions = TickActions;
            this.ExitActions = ExitActions;
            this.HitReaction = HitReaction;
            this.ViewAnimId = ViewAnimId;
            this.ViewBackAnimId = ViewBackAnimId;
            this.ViewEndAnimId = ViewEndAnimId;
            EndInit();
        }

        public readonly int Id;
        public readonly string Name;
        public readonly System.Collections.Generic.List<float> HalfExtents;
        public readonly int TotalTimeMs;
        public readonly int TickTimeMs;
        public readonly System.Collections.Generic.List<int> EnterActions;
        public readonly System.Collections.Generic.List<int> TickActions;
        public readonly System.Collections.Generic.List<int> ExitActions;
        public readonly skillconfig.HitReaction HitReaction;
        public readonly int ViewAnimId;
        public readonly int? ViewBackAnimId;
        public readonly int? ViewEndAnimId;

        public  void ResolveRef()
        {
            HitReaction?.ResolveRef();
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

