
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.skillconfig
{
public partial class AreaParams : Singleton<AreaParams>
{
    private readonly System.Collections.Generic.Dictionary<int, skillconfig.AreaParam> _dataMap;

    public AreaParams(System.Collections.Generic.Dictionary<int, skillconfig.AreaParam> dataMap)
    {
        _dataMap = dataMap;
    }

    public System.Collections.Generic.Dictionary<int, skillconfig.AreaParam> GetAll() => _dataMap;
    public System.Collections.Generic.IReadOnlyDictionary<int, skillconfig.AreaParam> DataMap => _dataMap;
    public skillconfig.AreaParam GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public skillconfig.AreaParam Get(int key) => _dataMap[key];
    public skillconfig.AreaParam this[int key] => _dataMap[key];

    public void ResolveRef()
    {
        foreach (var _v in _dataMap.Values)
        {
            _v.ResolveRef();
        }
        EndRef();
    }

    partial void EndRef();
}
}

