
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.skillconfig
{
public partial class BuffParams : Singleton<BuffParams>
{
    private readonly System.Collections.Generic.Dictionary<int, skillconfig.BuffParam> _dataMap;

    public BuffParams(System.Collections.Generic.Dictionary<int, skillconfig.BuffParam> dataMap)
    {
        _dataMap = dataMap;
    }

    public System.Collections.Generic.Dictionary<int, skillconfig.BuffParam> GetAll() => _dataMap;
    public System.Collections.Generic.IReadOnlyDictionary<int, skillconfig.BuffParam> DataMap => _dataMap;
    public skillconfig.BuffParam GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public skillconfig.BuffParam Get(int key) => _dataMap[key];
    public skillconfig.BuffParam this[int key] => _dataMap[key];

    public void ResolveRef()
    {
        foreach (var _v in _dataMap.Values)
        {
            _v.ResolveRef();
        }
        EndRef();
    }

    partial void EndRef();
}
}

