
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET.skillconfig
{
    public sealed partial class BuffParam : ET.Object
    {
        public BuffParam(int Id, string Name, int DurationMs, int TickTimeMs, int MaxStacks, bool RefreshOnApply, System.Collections.Generic.List<int> AddActions, System.Collections.Generic.List<int> TickActions, System.Collections.Generic.List<int> RemoveActions) 
        {
            this.Id = Id;
            this.Name = Name;
            this.DurationMs = DurationMs;
            this.TickTimeMs = TickTimeMs;
            this.MaxStacks = MaxStacks;
            this.RefreshOnApply = RefreshOnApply;
            this.AddActions = AddActions;
            this.TickActions = TickActions;
            this.RemoveActions = RemoveActions;
            EndInit();
        }

        public readonly int Id;
        public readonly string Name;
        public readonly int DurationMs;
        public readonly int TickTimeMs;
        public readonly int MaxStacks;
        public readonly bool RefreshOnApply;
        public readonly System.Collections.Generic.List<int> AddActions;
        public readonly System.Collections.Generic.List<int> TickActions;
        public readonly System.Collections.Generic.List<int> RemoveActions;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

