
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET.skillconfig
{
    public sealed partial class BulletParam : ET.Object
    {
        public BulletParam(int Id, string Name, float Speed, int TotalTimeMs, bool DestroyOnHit, int HitResetIntervalMs, System.Collections.Generic.List<float> HalfExtents, System.Collections.Generic.List<float> SpawnOffset, System.Collections.Generic.List<float> ViewOffset, bool ViewGrounded, int ViewAnimId, skillconfig.HitReaction HitReaction, System.Collections.Generic.List<int> HitActions) 
        {
            this.Id = Id;
            this.Name = Name;
            this.Speed = Speed;
            this.TotalTimeMs = TotalTimeMs;
            this.DestroyOnHit = DestroyOnHit;
            this.HitResetIntervalMs = HitResetIntervalMs;
            this.HalfExtents = HalfExtents;
            this.SpawnOffset = SpawnOffset;
            this.ViewOffset = ViewOffset;
            this.ViewGrounded = ViewGrounded;
            this.ViewAnimId = ViewAnimId;
            this.HitReaction = HitReaction;
            this.HitActions = HitActions;
            EndInit();
        }

        public readonly int Id;
        public readonly string Name;
        public readonly float Speed;
        public readonly int TotalTimeMs;
        public readonly bool DestroyOnHit;
        public readonly int HitResetIntervalMs;
        public readonly System.Collections.Generic.List<float> HalfExtents;
        public readonly System.Collections.Generic.List<float> SpawnOffset;
        public readonly System.Collections.Generic.List<float> ViewOffset;
        public readonly bool ViewGrounded;
        public readonly int ViewAnimId;
        public readonly skillconfig.HitReaction HitReaction;
        public readonly System.Collections.Generic.List<int> HitActions;

        public  void ResolveRef()
        {
            HitReaction?.ResolveRef();
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

