
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET.skillconfig
{
    public sealed partial class ButtonMapping : ET.Object
    {
        public ButtonMapping(int Button, int SkillId) 
        {
            this.Button = Button;
            this.SkillId = SkillId;
            EndInit();
        }

        public readonly int Button;
        public readonly int SkillId;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

