
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET.skillconfig
{
    public sealed partial class HitEvent : ET.Object
    {
        public HitEvent(int Phase, skillconfig.HitTrigger On, skillconfig.HitPolicy HitPolicy, skillconfig.HitEventKind Kind, int? NextPhase, int? NextSkillId, int? BuffId) 
        {
            this.Phase = Phase;
            this.On = On;
            this.HitPolicy = HitPolicy;
            this.Kind = Kind;
            this.NextPhase = NextPhase;
            this.NextSkillId = NextSkillId;
            this.BuffId = BuffId;
            EndInit();
        }

        public readonly int Phase;
        public readonly skillconfig.HitTrigger On;
        public readonly skillconfig.HitPolicy HitPolicy;
        public readonly skillconfig.HitEventKind Kind;
        public readonly int? NextPhase;
        public readonly int? NextSkillId;
        public readonly int? BuffId;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

