
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.skillconfig
{ 
    public enum HitEventKind
    {
        nextPhase = 0,
        nextSkill = 1,
        grab = 2,
        addBuff = 3,
    }

} 

