
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.skillconfig
{ 
    public enum HitPolicy
    {
        FirstHitInCast = 0,
        FirstHitInPhase = 1,
        OncePerTargetInPhase = 2,
        EveryResolvedHit = 3,
    }

} 

