
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET.skillconfig
{
    public sealed partial class HitReaction : ET.Object
    {
        public HitReaction(int Phase, int Damage, int HitstunMs, float KbX, float LaunchY, int ProcBuffId, int ProcChance) 
        {
            this.Phase = Phase;
            this.Damage = Damage;
            this.HitstunMs = HitstunMs;
            this.KbX = KbX;
            this.LaunchY = LaunchY;
            this.ProcBuffId = ProcBuffId;
            this.ProcChance = ProcChance;
            EndInit();
        }

        public readonly int Phase;
        public readonly int Damage;
        public readonly int HitstunMs;
        public readonly float KbX;
        public readonly float LaunchY;
        public readonly int ProcBuffId;
        public readonly int ProcChance;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

