
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.skillconfig
{ 
    public enum HitTrigger
    {
        hit = 0,
        resolvedHit = 1,
        targetHit = 2,
    }

} 

