
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET.skillconfig
{
    public sealed partial class ManualBox : ET.Object
    {
        public ManualBox(int Phase, int OnMs, int OffMs, System.Collections.Generic.List<float> Offset, System.Collections.Generic.List<float> Half) 
        {
            this.Phase = Phase;
            this.OnMs = OnMs;
            this.OffMs = OffMs;
            this.Offset = Offset;
            this.Half = Half;
            EndInit();
        }

        public readonly int Phase;
        public readonly int OnMs;
        public readonly int OffMs;
        public readonly System.Collections.Generic.List<float> Offset;
        public readonly System.Collections.Generic.List<float> Half;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

