
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET.skillconfig
{
    public partial struct Movement
    {
        public Movement(float Distance, int DurationMs, bool StopOnHit) 
        {
            this.Distance = Distance;
            this.DurationMs = DurationMs;
            this.StopOnHit = StopOnHit;
            PostInit();
        }

        public readonly float Distance;
        public readonly int DurationMs;
        public readonly bool StopOnHit;

        partial void PostInit();
    }

}

