
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.skillconfig
{ 
    public enum NextTrigger
    {
        none = 0,
        phaseEnd = 1,
        hit = 2,
        key = 3,
    }

} 

