
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET.skillconfig
{
    public sealed partial class Phase : ET.Object
    {
        public Phase(int AnimId, int DurationMs, int CancelMs, int? CancelButton, bool ClearHitTargets, int SuperArmorMs, skillconfig.Movement Movement, int? NextPhase, int NextSkillId, skillconfig.NextTrigger NextTrigger, bool? EndOnLanding) 
        {
            this.AnimId = AnimId;
            this.DurationMs = DurationMs;
            this.CancelMs = CancelMs;
            this.CancelButton = CancelButton;
            this.ClearHitTargets = ClearHitTargets;
            this.SuperArmorMs = SuperArmorMs;
            this.Movement = Movement;
            this.NextPhase = NextPhase;
            this.NextSkillId = NextSkillId;
            this.NextTrigger = NextTrigger;
            this.EndOnLanding = EndOnLanding;
            EndInit();
        }

        public readonly int AnimId;
        public readonly int DurationMs;
        public readonly int CancelMs;
        public readonly int? CancelButton;
        public readonly bool ClearHitTargets;
        public readonly int SuperArmorMs;
        public readonly skillconfig.Movement Movement;
        public readonly int? NextPhase;
        public readonly int NextSkillId;
        public readonly skillconfig.NextTrigger NextTrigger;
        public readonly bool? EndOnLanding;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

