
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.skillconfig
{
[ConfigProcess(ConfigType.Code)]
public partial class SkillButtonMappings : Singleton<SkillButtonMappings>, IConfig
{
    private readonly System.Collections.Generic.Dictionary<int, skillconfig.ButtonMapping> _dataMap;

    public SkillButtonMappings(System.Collections.Generic.Dictionary<int, skillconfig.ButtonMapping> dataMap)
    {
        _dataMap = dataMap;
    }

    public System.Collections.Generic.Dictionary<int, skillconfig.ButtonMapping> GetAll() => _dataMap;
    public System.Collections.Generic.IReadOnlyDictionary<int, skillconfig.ButtonMapping> DataMap => _dataMap;
    public skillconfig.ButtonMapping GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public skillconfig.ButtonMapping Get(int key) => _dataMap[key];
    public skillconfig.ButtonMapping this[int key] => _dataMap[key];

    public void ResolveRef()
    {
        foreach (var _v in _dataMap.Values)
        {
            _v.ResolveRef();
        }
        EndRef();
    }

    partial void EndRef();
}
}

