
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET.skillconfig
{
    public sealed partial class SkillParam : ET.Object
    {
        public SkillParam(int Id, string Name, skillconfig.SkillType Type, int CooldownMs, int TotalTimeMs, bool RequireAirborne, bool ManualCooldown, int MinCastHpPct, int CastHpCostPct, int? EntryPhase, int? AirborneEntryPhase, System.Collections.Generic.List<skillconfig.Phase> Phases, System.Collections.Generic.List<skillconfig.HitReaction> HitReactions, System.Collections.Generic.List<int> HitActions, System.Collections.Generic.List<skillconfig.ManualBox> ManualBoxes, System.Collections.Generic.List<skillconfig.SpawnEvent> SpawnEvents, System.Collections.Generic.List<skillconfig.HitEvent> HitEvents) 
        {
            this.Id = Id;
            this.Name = Name;
            this.Type = Type;
            this.CooldownMs = CooldownMs;
            this.TotalTimeMs = TotalTimeMs;
            this.RequireAirborne = RequireAirborne;
            this.ManualCooldown = ManualCooldown;
            this.MinCastHpPct = MinCastHpPct;
            this.CastHpCostPct = CastHpCostPct;
            this.EntryPhase = EntryPhase;
            this.AirborneEntryPhase = AirborneEntryPhase;
            this.Phases = Phases;
            this.HitReactions = HitReactions;
            this.HitActions = HitActions;
            this.ManualBoxes = ManualBoxes;
            this.SpawnEvents = SpawnEvents;
            this.HitEvents = HitEvents;
            EndInit();
        }

        public readonly int Id;
        public readonly string Name;
        public readonly skillconfig.SkillType Type;
        public readonly int CooldownMs;
        public readonly int TotalTimeMs;
        public readonly bool RequireAirborne;
        public readonly bool ManualCooldown;
        public readonly int MinCastHpPct;
        public readonly int CastHpCostPct;
        public readonly int? EntryPhase;
        public readonly int? AirborneEntryPhase;
        public readonly System.Collections.Generic.List<skillconfig.Phase> Phases;
        public readonly System.Collections.Generic.List<skillconfig.HitReaction> HitReactions;
        public readonly System.Collections.Generic.List<int> HitActions;
        public readonly System.Collections.Generic.List<skillconfig.ManualBox> ManualBoxes;
        public readonly System.Collections.Generic.List<skillconfig.SpawnEvent> SpawnEvents;
        public readonly System.Collections.Generic.List<skillconfig.HitEvent> HitEvents;

        public  void ResolveRef()
        {
            foreach (var _e in Phases) { _e?.ResolveRef(); }
            foreach (var _e in HitReactions) { _e?.ResolveRef(); }
            foreach (var _e in ManualBoxes) { _e?.ResolveRef(); }
            foreach (var _e in SpawnEvents) { _e?.ResolveRef(); }
            foreach (var _e in HitEvents) { _e?.ResolveRef(); }
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

