
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.skillconfig
{ 
    public enum SkillType
    {
        MeleeCombo = 0,
        Dash = 1,
        Projectile = 2,
        AreaBurst = 3,
        Buff = 4,
    }

} 

