
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.skillconfig
{
public partial class SkillParams : Singleton<SkillParams>
{
    private readonly System.Collections.Generic.Dictionary<int, skillconfig.SkillParam> _dataMap;

    public SkillParams(System.Collections.Generic.Dictionary<int, skillconfig.SkillParam> dataMap)
    {
        _dataMap = dataMap;
    }

    public System.Collections.Generic.Dictionary<int, skillconfig.SkillParam> GetAll() => _dataMap;
    public System.Collections.Generic.IReadOnlyDictionary<int, skillconfig.SkillParam> DataMap => _dataMap;
    public skillconfig.SkillParam GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public skillconfig.SkillParam Get(int key) => _dataMap[key];
    public skillconfig.SkillParam this[int key] => _dataMap[key];

    public void ResolveRef()
    {
        foreach (var _v in _dataMap.Values)
        {
            _v.ResolveRef();
        }
        EndRef();
    }

    partial void EndRef();
}
}

