
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET.skillconfig
{
    public sealed partial class SpawnEvent : ET.Object
    {
        public SpawnEvent(int Phase, int AtMs, int AtFrame, skillconfig.TimeBase TimeBase, skillconfig.SpawnKind Kind, int? AreaId, int? BulletId, int? BuffId, int? AnimId, skillconfig.SpawnAt At, float Dist, int? DurationMs, int? Button, bool? ConsumeInput, int? UntilMs) 
        {
            this.Phase = Phase;
            this.AtMs = AtMs;
            this.AtFrame = AtFrame;
            this.TimeBase = TimeBase;
            this.Kind = Kind;
            this.AreaId = AreaId;
            this.BulletId = BulletId;
            this.BuffId = BuffId;
            this.AnimId = AnimId;
            this.At = At;
            this.Dist = Dist;
            this.DurationMs = DurationMs;
            this.Button = Button;
            this.ConsumeInput = ConsumeInput;
            this.UntilMs = UntilMs;
            EndInit();
        }

        public readonly int Phase;
        public readonly int AtMs;
        public readonly int AtFrame;
        public readonly skillconfig.TimeBase TimeBase;
        public readonly skillconfig.SpawnKind Kind;
        public readonly int? AreaId;
        public readonly int? BulletId;
        public readonly int? BuffId;
        public readonly int? AnimId;
        public readonly skillconfig.SpawnAt At;
        public readonly float Dist;
        public readonly int? DurationMs;
        public readonly int? Button;
        public readonly bool? ConsumeInput;
        public readonly int? UntilMs;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

