
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.skillconfig
{ 
    public enum SpawnKind
    {
        createArea = 0,
        createBullet = 1,
        superArmor = 2,
        playAnim = 3,
        addBuff = 4,
    }

} 

