
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.skillconfig
{ 
    public enum TimeBase
    {
        CastTime = 0,
        PhaseTime = 1,
        AnimationFrame = 2,
        PhaseEnter = 3,
        PhaseEnd = 4,
        Landing = 5,
        Input = 6,
    }

} 

